exclude: [ 'node_modules',
           'bower_components',
           'less',
           'package.json',
           'bower.json',
           'README.md',
           'gulpfile.js',
           'app.sublime-workspace',
           'app.sublime-project' ]